# Site settings
title: Ryan's Website
email: your-email@domain.com
description: "This is a sample Github.io test site."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
